name: flutx
description: Flutter State Manager + UI Library
version: 0.2.0-dev.1
homepage: https://github.com/denishnavadiya123/flutx.git

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  http: ^0.13.6
  provider: ^6.0.5
  flutter_svg: ^2.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/two_tone/mdi/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: BoxIcons
      fonts:
        - asset: assets/icons/BoxIcons.ttf
    - family: Symbols
      fonts:
        - asset: assets/icons/material-symbol.ttf
          weight: 300
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
